### ISSUE TITLE
Displaying tooltips only on original datapoints

### ISSUE THREAD

**Issue by philipgoh** [MichaelZinsmaier/CurvedLines#26]
Is there a way of displaying tooltips for the original data points but not for the "helper" data points added to smooth the lines? 

For an example, please see this [fiddle](https://jsfiddle.net/e6yh5fv3/3/). Is there any way to have tooltips appearing only on the original 24 data points?

**Comment by MichaelZinsmaier** [comment]
yep there is, you have to draw the original points again.

   - 1x original points -> transformation into new set of points -> curved line
   - 1x original points -> interaction with original points

like that https://jsfiddle.net/rt58Lyr2/
flot allows you to tewak the settings for an overall graph as well as for individual lines => curvedLines on, off, hover on, off ...

to make it really good of course you would have to adapt colors etc. as well
