### ISSUE TITLE
Smoothing doesn't work on non ordered data

### ISSUE THREAD

**Issue by basbloemsaat** [MichaelZinsmaier/CurvedLines#28]
As I tried to used curvedLines on a time series, I failed. After much eliminating, it seemed that it fails with non ordered data, eg the following does not smooth:

    var d2 = [[1431129600000, 1004 ] , [1426377600000, 1023 ] , [1421539200000, 1018 ] ,
    [1421452800000, 1022 ] , [1420934400000, 1004 ] , [1420848000000, 1003 ] , 
    [1417219200000, 998 ] , [1414281600000, 993 ] , [1411257600000, 996 ] ];

http://jsfiddle.net/nojrc6hp/

**Comment by MichaelZinsmaier** [comment]
Hi basbloemsaat,

thats correct, CurvedLines assumes ordered data with distinct x values. The reasoning is that
you can easily sort your data in advance but other users that have sorted data shouldn't pay
the performance costs for sorting.

I will add a comment to the readme

Best Michael

**Comment by basbloemsaat** [comment]
Okay, thanks. It would have saved me a few hours to figure that out. Perhaps noting it in the docs will prevent others from chasing the same phantoms. Cheers!
