### ISSUE TITLE
Curveing only selected series

### ISSUE THREAD

**Issue by Dima4ka** [MichaelZinsmaier/CurvedLines#29]
I wanted to have a scattered and line (curved line) plot on the same canvas.
However, plugin "curves" all series in the plot. Any way (maybe parameter?) I can deal with it?

**Comment by MichaelZinsmaier** [comment]
Hi have a look at the new example: https://jsfiddle.net/L0kgfytv/
The apply parameter allows you to toogle curving per series

Best Michael
