### ISSUE TITLE
differentiating between "real" datapoints and interpolated spline points

### ISSUE THREAD

**Issue by kenirwin** [MichaelZinsmaier/CurvedLines#30]
I've been working on getting CurvedLines to work with the flot.tooltip plugin [https://github.com/krzysu/flot.tooltip] , and I'd like to be able to tell the difference between a "real" datapoint (ie, one that's actually defined in the user input data) vs. the dozens of points that are created by CurvedLines. Is there currently a way to do this? I'm hoping that either for each series or for each point, there would be a parameter such as: 
this.plotOptions.series.curvedLines.data-type == "real-data" || "interpolated-data"
or something like this. 

Can you suggest either a way of detecting this using the plugin as it is, or where I might look to insert such a datum into CurvedLines current output? I've puzzled over the code, but I can't figure out where one might start to implement such a thing.

**Comment by MichaelZinsmaier** [comment]
Hi have a look at the new example: https://jsfiddle.net/L0kgfytv/

You either want to replot the data => plot it once in a curved form without tooltips and once ontop with only the original data points and tooltip. If you need some kind of annotation on the data itself you would have to look at curvedLines.js Line 204 to 212 add point is the original data point, the curve points are the fake data points (for the new v1 alogrithm)

**Comment by kenirwin** [comment]
Thanks -- I am hoping that there would be an annotation in the data itself that could be use later by other plugins, so I'll have a look at those lines and see what seems possible.

Thanks
