### ISSUE TITLE
Not versioned and published

### ISSUE THREAD

**Issue by beruic** [MichaelZinsmaier/CurvedLines#32]
Could you perhaps version this library and publish it through a CDN (e.g. CDNJS)?
That would make it much more accesbile.

**Comment by MichaelZinsmaier** [comment]
it is actually versioned currently 1.1.1 (see curvedLines.js and Releases)
you can also find it here http://bower.io/search/?q=curvedlines or here https://rails-assets.org/  

regarding a CDN https://rawgit.com/ is often quite helpful (-:

**Comment by beruic** [comment]
Yeah. I'm using [https://raw.githubusercontent.com/MichaelZinsmaier/CurvedLines/2fb652f8231fe7733eda8d1da35b8d4eea34ab9f/curvedLines.js](https://raw.githubusercontent.com/MichaelZinsmaier/CurvedLines/2fb652f8231fe7733eda8d1da35b8d4eea34ab9f/curvedLines.js) for now :)
It's obtained by browsing the code by the time of the latest commit, and taking the raw content of the file by then. This way I avoid breaking changes on updates, but I may also miss an update.

**Comment by beruic** [comment]
Thank you for pointing me to rawgit. Looks quite exciting :)

**Comment by beruic** [comment]
Could you perhaps add tags for versions, så i can get a CDN link which is not likely to change content?

**Comment by beruic** [comment]
Screw me, it's already there! :D
Just needed to supply
[https://github.com/MichaelZinsmaier/CurvedLines/blob/1.1.1/curvedLines.js](https://github.com/MichaelZinsmaier/CurvedLines/blob/1.1.1/curvedLines.js) to get 
[https://cdn.rawgit.com/MichaelZinsmaier/CurvedLines/1.1.1/curvedLines.js](https://cdn.rawgit.com/MichaelZinsmaier/CurvedLines/1.1.1/curvedLines.js). Would be nice if GitHub could link to tagged versions of files on CDN automatically :)
