### ISSUE TITLE
Better documentation on how to link

### ISSUE THREAD

**Issue by beruic** [MichaelZinsmaier/CurvedLines#33]
To make it easy for users to use the library, you could supply the latest stable RawGit CDN link in the readme. To make it easy for people to use this CDN with fallback you could supply  an expression to test whether the library has been loaded properly. Here is an example of CDN with fallback using jquery.

```javascript
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>(window.jQuery)||document.write('<script src="/lib/jquery/script"><\/script>');</script>
```

Just switch `window.jQuery` with somthing that evaluates to `true` if CurvedLines has been loaded correctly like so:

```javascript
<script src="https://cdn.rawgit.com/MichaelZinsmaier/CurvedLines/1.1.1/curvedLines.js"></script>
<script>([curvedlines_detection_expression])||document.write('<script src="[server_local_copy]"><\/script>');</script>
```

**Comment by MichaelZinsmaier** [comment]
hey, 

I added a readme snippet with a RawGit link, however I could not find a good expression for testing the lib status. I think it would be something like this 

<script>
  ($.plot.plugins.find(function(p) { return p.name === 'curvedLines' }) != 'undefined')||document.write('<script src="/libs/curvedLines.js"><\/script>');
</script>

but I was not able to get it really working + it should be a general solution ...
If you have a suggestion for this I would be happy to include it.

**Comment by beruic** [comment]
First of all, I only see a line break above where it looks like there should be something :)

Secondly, I must admit that I am not very much into how flot plugins work, but is it possible to ask flot which plugins it has loaded?

**Comment by MichaelZinsmaier** [comment]
yep there should be something (-:

flot plugins are registered like this
````
$.plot.plugins.push({
		init : init,
		options : options,
		name : 'curvedLines',
		version : '1.1.1'
	});
````

and this code snippet checks if curvedLines has been loaded
but thats the catch it will only work after the registration code of curvedLines has been exectued
and JQuery has been loaded ...
````
var match = $.grep($.plot.plugins, function(plugin, i){
  return plugin.name == 'curvedLines';
})

if (match.length == 1) {
  alert("loaded")
} else {
  alert("nope")
}
````

**Comment by beruic** [comment]
Well, the job of the fallback is to load the local version if the CDN fails, so if we just asume that jQuery and plot has been loaded. You need to make it a one-liner however.

I might get time to look at it later today, but as far as I can see, the following should work:

```javascript
<script src="https://cdn.rawgit.com/MichaelZinsmaier/CurvedLines/1.1.1/curvedLines.js"></script>
<script>($.grep($.plot.plugins, function(plugin, i){return plugin.name == 'curvedLines';}).length == 1)||document.write('<script src="[server_local_copy]"><\/script>');</script>
```

I have not tested though.
Why do you test on `.length == 1`?
Wouldn't `plugin.name == 'curvedLines'` return a boolean value you can test on directly?

**Comment by beruic** [comment]
Just read up on `jQuery.grep()`. Looks good to me.

**Comment by beruic** [comment]
This seems to work, and is shorter, easier to understand, and faster if there are many plugins:

```javascript
$.plot.plugins.find(function(element){return element.name == "curvedLines"})
```

So that will become:

```javascript
<script src="https://cdn.rawgit.com/MichaelZinsmaier/CurvedLines/1.1.1/curvedLines.js"></script>
<script>$.plot.plugins.find(function(element){return element.name == "curvedLines"})||document.write('<script src="[server_local_copy]"><\/script>');</script>
```

**Comment by MichaelZinsmaier** [comment]
thy, I added everything to the Readme!
